### ISSUE TITLE
xGov Voting Session 3: Proposer Reddit AMA

### ISSUE THREAD

**Issue by fredestante** [algorandfoundation/xGov#172]
Hi xGov Proposers,

This is an open invitation for the “xGov Proposer Reddit MEGA AMA” to be held on Thursday, February 8th 2024 at https://www.reddit.com/r/AlgorandOfficial

This event will be an opportunity for the community to ask questions to any proposals currently being reviewed ahead of voting session 3.

**Structure of the AMA**

AMA to start on February 8th at 4pm UTC - this is when projects start responding to community questions 
Projects can continue to answer and engage with the community once the 2h period is over, but all participants are encouraged to be active during this time slot.

**How to sign up for the AMA as a xGov grant proposer**

You must respond to this github issue from the same account as you sent your xGov proposal with the following information:

Name: Name of your project
Description: Short description of your project (500 characters max - it will be capped at that limit)
Link: One link to your project (website, social media, etc)
Submission Link: The link to your xGov Proposal
Amount Requested: The amount requested in your xGov Proposal
Reddit username: Reddit usernames of everyone from your team that will answer questions from the community. These accounts will receive a special flair to indicate which project they are affiliated with

**Deadline**

The deadline to sign up for the Reddit AMA is February 7th at 8pm UTC.

**AMA logistics**

The AMA on Reddit will feature all projects that sign up in this github issue, and they will be added to the post in the order they are registered here.

**Rules**

Review all the rules of our sub before making your comments. The rules are available on the sidebar at https://www.reddit.com/r/AlgorandOfficial.

**Comment by SilentRhetoric** [comment]
Name: AlgoDirectory
Description: AlgoDirectory will help people discover all that the Algorand ecosystem has to offer while enabling users to easily create & edit listings through an on-chain model. The Directory will become permissionless and sustainable by leveraging Algorand’s powerful capabilities to put listings on chain and let owners maintain them through a novel “Vouching Protocol” smart contract.
Link: https://algodirectory.app
Submission Link: https://forum.algorand.org/t/xgov-123-algodirectory-directory-algo/11078
Amount Requested: 50,000
Reddit username: @SilentRhetoric @tak-o-kat

**Comment by SilentRhetoric** [comment]
Name: Community Code Contribution Contest (C4)
Description: The Community Code Contribution Contest (C4) will be an ARC-34-compliant community contest among developers in the Algorand ecosystem to contribute high-quality features and bug fixes to the core code libraries that make Algorand work. The contest will also generate recognition for winning developers on social media to bring attention to their efforts to make Algorand’s codebase better.
Link: N/A
Submission Link: https://forum.algorand.org/t/xgov-130-community-code-contribution-contest-c4/11230
Amount Requested: 44,444
Reddit username: @SilentRhetoric

**Comment by headline-design** [comment]
Name: XBallot - DAO Management Platform
Description: XBallot is a comprehensive governance protocol that allows users to create and manage DAOs on the Algorand blockchain. The protocol includes a variety of features that enable users to create and manage DAOs, including: voting, proposals, treasury, and more. The protocol is also fully decentralized, featuring a unique on-chain data aggregation system that allows users to interact with the protocol directly from their Algorand wallet. 
Link: https://xballot.net
GitHub Link: https://github.com/headline-design/xballot
Submission Link: https://github.com/algorandfoundation/xGov/pull/107
Forum Link: https://forum.algorand.org/t/xballot-advancing-dao-management-on-algorand/9823
Amount Requested: 375,000
Reddit username: u/ussaaron

**Comment by shivamanupadi** [comment]
Name: Pixelnode: One-click node manager
Description: PixelNode is a user-friendly One-click node solution for Algorand node management.
Offering a seamless installation process and an intuitive web interface for easy interaction with Algorand nodes.
Link: https://pixelnode.org
Submission Link: https://github.com/algorandfoundation/xGov/pull/110
Amount Requested: 250,000
Reddit username: u/shivaprasadmanupadi

**Comment by Vidhyanandcs** [comment]
Name: Notiboy web3 chat (Milestone 2) Group Chat, Encryption and NFD integration
Description: We at Notiboy has a vision to make web3 communication more efficient. That means the algorand addresses should be able to communicate with each other by maintaining their privacy.
Link: https://notiboy.com/
Submission Link: https://github.com/algorandfoundation/xGov/pull/104/files
Amount Requested: 60,000
Reddit username: u/semanticweb

**Comment by Vidhyanandcs** [comment]
Name: Airgap vault & wallet integration via isolated modules
Description: irgap vault is an open-source vault that helps algorand community  to convert their old mobile phone to a cold storage for generation and management of private keys. Airgap wallet is an open-source wallet with web, android, iOS, mac, windows and linux support.
Link: https://airgap.it/
Submission Link: https://github.com/algorandfoundation/xGov/pull/108/files
Amount Requested: 84,530
Reddit username: u/semanticweb

**Comment by dolphinkitty** [comment]
Name: xGov 170: Decentralized Voting & Agreement Signing for Everyone
Description: A new voting and agreement signing tool that enables any user, brand, or community to deploy custom contracts for streamlined proposal creation, decentralized voting, encrypted agreement signing, and immutable record keeping. By providing essential collaboration and decision-making features within a highly intuitive user-experience, we aim to attract, target, and onboard teams and businesses primarily from outside the Algorand ecosystem.
Link: Launching soon
Submission Link: https://github.com/algorandfoundation/xGov/pull/170/files
Amount Requested: 125000
Reddit username: u/wow_everything

**Comment by heartberg** [comment]
Name: xGov 170: Decentralized Voting & Agreement Signing for Everyone
Description: A new voting and agreement signing tool that enables any user, brand, or community to deploy custom contracts for streamlined proposal creation, decentralized voting, encrypted agreement signing, and immutable record keeping. By providing essential collaboration and decision-making features within a highly intuitive user-experience, we aim to attract, target, and onboard teams and businesses primarily from outside the Algorand ecosystem.
Link: Launching soon
Submission Link: https://github.com/algorandfoundation/xGov/pull/170/files
Amount Requested: 125000
Reddit username: u/wow_everything

**Comment by ChainTrail** [comment]
Name: Chaintrail - Uncovering Algorand

Description: We'll be unraveling the landscape of Real-World Assets tokenized on Algorand. Showing web2 and web3 consumers that Algorand is 'the' blockchain best suited for RWA (using actual on-chain data). Made by Chaintrail, a blockchain intelligence & insights platform focussed on uncovering Algorand in full (Dapp impact, NFT's, RWA, Network insights, TVL, Stables, ...)

Link: https://chaintrail.io

Submission Link: https://forum.algorand.org/t/xgov-109-unraveling-algorands-real-world-assets-landscape-dex-swaps/11226

Amount Requested: 95000

Reddit username: u/Lea-Chaintrail

**Comment by solluna168** [comment]
x Gov 143
 Educational Fungi Farm
author: Solluna168 aka stinky bird
discussions-to: https://forum.algorand.org/u/solluna168/activity/pending
company_name: Solluna Mushroom Farm LLC
category: Community
amount_requested: 55000



## Abstract
Solluna Mushroom Farms is a farm-to-table business that is adopting Algorand's blockchain technology to educate/onboard mushroom growers and buyers.
We aim to achieve this by implementing the following key features to our business plan: (1) an ASA (Algorand Standard Asset) rewards only program for our customers and supporters, (2) an NFT based grow kit and farming course, and (3) an innovative regenerative sustainablity mushroom farm. We are requesting funding in order to execute these key features.




#### SPORE Token
The farm will incorporate the SPORE token into the business model by giving holders discounts on our products. SPORE will be sent to clients that participate in our discord and Texas holdem poker tournaments.

#### NFTs
We plan on creating mushroom grow kits with NFTs associated to each type of kit. These NFTs will have information about the fungus, a spore print, how to grow and take care of your new fungus.

#### Mushroom Courses
Our courses will assist new growers with retaining existing mushroom farm practices that can be easily transferred to their own farms. These courses will also include basic understanding of the Algorand ecosystem and technology. We will be doing this in order to prepare our clients for future collaborations.

#### Environmentally Friendly Farm
Our farms will be producing fungi by using recycled plastic with outdoor elements that will assist in healthy fungus. These farms will run off solar, wind, and hydropower at some locations. Solluna Farms will be the first full scale fungi farm to use reusables!

## Future Blueprint
Online educational platform to teach crypto and fungi cultivation. Online marketplace full of wellness products, and mushroom cultivation supplies. Using the chain to track rewards for discounts using SPORE coin.

## Benefits for the community

#### Genuine Rewards Program
The SPORE token’s only purpose is as a rewards and discount token for our products. This token will not be available on decentralized exchanges or other decentralized finance applications. SPORE can be used with our products to get up to a 20% discount, the amount of SPORE needed to get the full 20% discount will be voted on by our community.

#### Educational
The on-boarding of new Algorand users will occur with each new student that completes our courses. Courses will explain how the Algorand blockchain works and how we integrate our farms with the technology.

#### Unique NFT use case
Each type of grow kit for a particular fungus will come with an NFT that provides detailed information on what the grower has purchased. This means for every grow kit sold, a grower will use the Algorand chain in order to read their instructions and get more information about the fungus.



#### Environmentally focused
Cultivating fungi is not very environmentally friendly. The majority of large farms use plastics for growth and never attempt to achieve the scale and sustainability of a regenerative farm. The creative reuse of bags, the use of solar, and wind power by Solluna Farms will significantly alter the way that mushrooms are grown on a wide scale. The adoption of fungus will begin with educational courses. Since this will be the first application of NFTs in education, people will have a greater appreciation for what these devices are capable of. With practical classes offered around the state and online resources, we will instruct people on how to cultivate their own food and utilize technology responsibly in the Algorand Ecosystem.

Our two major goals will be to expand the Algorand blockchain and fungi farms. For ongoing research, the Oregon Solluna Farm will cultivate fungus with legal therapeutic properties. I currently work as a DSP for persons who have mental health issues. This product line will be put to the test in a variety of ways to demonstrate how fungi may actually benefit those in need. In the past I managed an Algorand NFT poker tournament. We had fifteen of the best NFT projects from Algorand on board. For our tournament we’ll be giving out courses, cross-chain games, mushroom rewards, and Algorand NFTs. Our hearts, souls, and considerable time has been going into this project. Working with mushrooms has shown the potential to significantly improve mental health and other health issues.

This company offers in-person workshops, mushroom foraging expeditions, and a gentle introduction to cryptocurrency and mushroom cultivation.

**Comment by dsmessman** [comment]
Name: pressdot
Description: pressdot is the first pay-per-view content monetization service on Algorand. Creators currently struggle to monetize their work effectively without using ads or subscriptions. pressdot provides an alternative method to share and monetize content, enabling more access for viewers, and more revenue for creators. 
Link: pressdotalgo.com
Submission Link: [xGov 118: pressdot - the First WebMarket](https://github.com/algorandfoundation/xGov/pull/118)
Amount Requested: 500,000
Reddit username: /u/pressdotdugan

**Comment by xxiled-plastic-cat** [comment]
Name: xGov 148 - CompX - CoinTracker+ #148
Description: 

> So you’ve found the next 100x coin, your excited! You bought some yesterday and you bought some today - but the price changed in that time - green candles of course! - but how does that affect your return? What’s your average buying price? What happened in between your buys, what was the volume?
>Coin Tracker+ is another innovative feature brought to you by CompX. Analytics are great but personalised analytics are even better. Select any coin/token/ASA/NFT and get a personalised dashboard related to your holdings, buying, selling, average prices and overall P+L. Find farming/staking opportunities to your holdings and get alerts on price changes.

Link: https://app.compx.io
Submission Link: [The link to your xGov Proposal](https://github.com/algorandfoundation/xGov/pull/148)
Amount Requested: 50,000
Reddit username: u/ktnelsonArt

**Comment by xxiled-plastic-cat** [comment]
Name: xGov-149 - CompX - Farm Rewards with Lock Weighting #149
Description: 
>At CompX we pride ourselves on bringing innovative solutions to the Algorand DeFi ecosystem. Our auto-compounding farms give users new strategies to earn higher yield in a more efficient manner. To further enhance our auto-compounding farm product we want to introduce a mechanism where users can yield additional rewards on top of the farm APR and the auto-compounding bonus.

Link: https://app.compx.io
Submission Link: [The link to your xGov Proposal](https://github.com/algorandfoundation/xGov/pull/149)
Amount Requested: 200,000
Reddit username: u/ktnelsonArt

**Comment by clooneyr** [comment]
Name: xGov-157: Centralised Bridge Proposal: Two-Way Cardano (ADA) to Algorand (Algo) [#157 ](https://github.com/algorandfoundation/xGov/pull/157)
Description: This proposal outlines the development of a centralised bridge facilitating the seamless transfer of Cardano (ADA) and Algorand (ALGO) between the two chains. The bridge aims to leverage the unique nature of the Cardano and Algorand relationship and provide users on both networks with a secure and efficient means to transfer and utilise assets across ecosystems
Link: [algomint](https://www.algomint.io/)
Submission Link: [The link to your xGov Proposal](https://github.com/algorandfoundation/xGov/pull/157)
Amount Requested: 260,000
Reddit username: https://www.reddit.com/user/TNTalgomint/

**Comment by atsoc1993** [comment]
Name: AlgoLearn; xGov-99
Description: The current resources for new developers are scattered and spread thin across several platforms with zero interactivity. AlgoLearn will bridge these gaps with interactive and detailed guides to programming, including rudimentary concepts needed before diving into Algorand SDKs.
Link: https://youtu.be/5SjGYC3Ub-0
Submission Link: https://forum.algorand.org/t/xgov-99-algolearn-platform-interactive-learning-for-new-developers/11282/9
Amount Requested: 120000
Reddit username: Atsoc1993

**Comment by madshapes-dev** [comment]
Name: xgov-95: Gamify Exploration and Engagement of NFT ecosystem with Open-source browser game [#95](https://github.com/algorandfoundation/xGov/pull/95/files)
Description: Develop a "match-2" open-source browser game with scoring to explore algorand NFT collections. It provides a very visual and engaging experience of discovering Algorand NFT scene. It can be used as a tool for giveaways and competitions to cheaply and easily drive extra activity to the projects. In the future we would like to expand this to become a crosschain platform to help with onboarding new NFT enthusiast to Algorand. You can try a POC version here: https://cosmic-match.vercel.app
Link: https://beta.cosmicchamps.com/
Submission Link: https://forum.algorand.org/t/xgov-95-open-source-match-2-browser-game-to-explore-nft-ecosystem/11086/
Amount Requested: 30 000
Reddit username: u/cc-simon , u/cosmicchamps



Name: xgov-152: Algorand is THE chain for Gaming (establishing the RWA narrative) [#152](https://github.com/algorandfoundation/xGov/pull/152/files)
Description: To establish the narrative that Algorand is great for gaming it is crucial that lead games are secure, performant and ideally built to appeal the masses (fun to play) - all of which Cosmic Champs is!
To date, we are the only game that supports real time 3d PVP, with authoritative servers on Algorand. To meet the demand, we seek funds to migrate our server fleet to a more powerful instances that will be able to handle sudden spikes in active game sessions better, ensuring smooth first impressions.
Link: https://beta.cosmicchamps.com/
Submission Link: https://forum.algorand.org/t/xgov-152-algorand-as-go-to-chain-for-gaming-establishing-the-rwa-narrative/11105/
Amount Requested: 100 000
Reddit username: u/cc-simon , u/cosmicchamps



Name: xgov-154: Cosmic Champs partnering with legendary indie toy company to bring physical toy in-game on Algorand [#154](https://github.com/algorandfoundation/xGov/pull/154/files)
Description: we are partnering with an established player in the collectible toy industry that holds brand IPs for action toys that are a perfect fit for our mobile game (imagine transformers or gundam IP being added to Cosmic Champs game). We will do a limited physical run of a the collectible toy (not a cosmic champs character) and integrate it in our game as NFT. Each figurine will have its NFT counterpart. That will open Algorand to a whole new audience of collectors to interact ecosystem.
Link: https://beta.cosmicchamps.com/
Submission Link: https://forum.algorand.org/t/xgov-154-cosmic-champs-partnering-with-legendary-indie-toy-company-to-bring-physical-toys-in-game-on-algorand/11109/
Amount Requested: 250 000
Reddit username: u/cc-simon , u/cosmicchamps

**Comment by LoafPickleWW** [comment]
Name: xGov 112 - Thurstober Tools - Onboarding Enhancements, Upgrades, and Redesign
Description: The Team at Thurstober Tools (Formerly Evil Tools) has listened to the community requests for new tools. In this proposal we want to add in NFD Vault Support to reduce the opt-friction for new Algorand Users, Add in the ability to enter an NFD root and airdrop to all the segements, Add ARC-36 Support (Non-Rarity Filters) to our Simple Mint and Update Tools, Add in advanced asset tools to change the Manager, Freeze, and Clawback Address, and add in a tool where you can enter a Wallet Address to download the tx history. Included in this proposal free of charge will also be a site re-design.
Link: https://thurstober.com/
Submission Link: https://github.com/algorandfoundation/xGov/pull/112/files
Amount Requested: 20,000A
Reddit username: u/loafpickle

**Comment by LoafPickleWW** [comment]
Name: xgov-113 - Thurstober Wallet Enhancer - Asset Details and Atomic Swaps
Description: Listening to community feedback, we want to enhance the wallet enhancer with this proposal! Users have requested Asset Details for when you click on an asset. This will show the asset information including the metadata and give the user the ability to add, opt out, or send right from that asset page. In addition we intend on allowing users to make trades where you can go on another wallet, select assets, and set up an atomic swap transfer for any algorand ASAs. 
Link: https://thurstober.com/
Submission Link: https://github.com/algorandfoundation/xGov/pull/113/files
Amount Requested: 20,000A
Reddit username: u/loafpickle

**Comment by LoafPickleWW** [comment]
Name: xgov-114 - Thurstober Claims - Easily Create and Claim Atomic Swaps
Description: This proposal has been highly requested from app developers on Discord and Telegram. Here users will be able to use new API endpoints to easily create automated swap links. This will help reduce the onboarding friction of having to add an ASA to claim something as the atomic swap will have the opt in and transfer in once signing. In addition to creating the ability for bots to tap into the website, we will be developing an example discord bot to make things easier to develop and have a manual swap creation feature, becuase why not? 
Link: https://thurstober.com/
Submission Link: https://github.com/algorandfoundation/xGov/pull/114/files
Amount Requested: 20,000A
Reddit username: u/loafpickle
